#!/bin/bash

# Colors for output
ORANGE='\033[0;33m'  # Highlight color
WHITE='\033[0;37m'   # Regular text color
NC='\033[0m'         # No Color

echo -e "${WHITE}========================================${NC}"
echo -e "${WHITE}Cloudflare Worker Project Setup${NC}"
echo -e "${WHITE}========================================${NC}"
echo ""

# Use command-line argument or environment variable for project name, fallback to prompt
if [ -n "$1" ]; then
    PROJECT_NAME="$1"
elif [ -n "$PROJECT_NAME" ]; then
    : # Use environment variable if set
else
    echo -e "${ORANGE}Enter the name of your project:${NC}"
    read -r PROJECT_NAME
fi

if [ -z "$PROJECT_NAME" ]; then
    echo -e "${ORANGE}No project name provided. Exiting.${NC}"
    exit 1
fi

echo -e "${WHITE}Creating project: $PROJECT_NAME${NC}"
echo ""

# Run create-cloudflare with CLI arguments for non-interactive setup
echo -e "${WHITE}Running create-cloudflare...${NC}"
echo -e "${ORANGE}This may take a few minutes while dependencies are installed...${NC}"
echo ""

npx create-cloudflare@latest --platform=workers "$PROJECT_NAME" \
    --category=hello-world \
    --type=hello-world \
    --lang=ts \
    --git=true \
    --deploy=false || {
    echo -e "${ORANGE}Error during create-cloudflare. Please check logs above and try manually if needed.${NC}"
    exit 1
}

echo ""
echo -e "${WHITE}Project initialization completed!${NC}"
echo ""

# Wait a moment for all file operations to complete
sleep 2

# Navigate to project directory
if [ ! -d "$PROJECT_NAME" ]; then
    echo -e "${ORANGE}Error: Project directory was not created. Exiting.${NC}"
    exit 1
fi

cd "$PROJECT_NAME" || {
    echo -e "${ORANGE}Error: Could not navigate to project directory.${NC}"
    exit 1
}

# Add comment to wrangler.jsonc
echo -e "${WHITE}Configuring wrangler.jsonc...${NC}"
TEMP_FILE=$(mktemp)
echo "// PLACE ENVIORNMENT VARIABLES OVER HERE INSTEAD OF .env BECAUSE ITS A WRANGLER PROJECT AND WRANGLER USES THIS FILE TO LOAD" > "$TEMP_FILE"
echo "// ENIVORNMENT VARIABLES" >> "$TEMP_FILE"
cat wrangler.jsonc >> "$TEMP_FILE"
mv "$TEMP_FILE" wrangler.jsonc

# Create README.md
echo -e "${WHITE}Creating README.md...${NC}"
cat > README.md << 'READMEEOF'
# Template Worker Project

This repository contains the codebase for a Cloudflare worker built with TypeScript and deployed using Cloudflare Workers. The project is structured to separate concerns, with controllers orchestrating logic by combining helpers, middlewares, models, and utils. Below is an explanation of the folder structure and the purpose of each file and directory.

## Folder Structure

### Root Directory

The root directory contains configuration files and dependencies for the project. Here's a breakdown of the files and folders:

- `node_modules/` \
  Contains all dependencies installed via npm or yarn. This folder is automatically generated when you run `npm install` or `yarn install`. Do not manually modify this folder, as it is managed by the package manager. Excluded from version control using `.gitignore`.

- `package.json`\
  The main configuration file for the Node.js project. It defines project metadata, scripts, dependencies, and devDependencies. Update this file to add new dependencies or scripts.

- `package-lock.json`\
  Automatically generated by npm to lock dependency versions, ensuring consistent installations across environments. Do not edit this file manually.

- `tsconfig.json`\
  The TypeScript configuration file for the project. It specifies compiler options like target JavaScript version, module system, and paths. Modify this file to adjust TypeScript settings, such as enabling strict type checking.

- `vitest.config.mts`\
  The configuration file for Vitest, the testing framework used in this project. It defines settings for running tests, such as test environment, file patterns, and coverage options. Update this file to customize test behavior.

- `worker-configuration.d.ts`\
  A TypeScript declaration file defining types for the worker configuration. Use this file to specify the structure of configuration objects used in the project.

- `wrangler.jsonc`\
  The configuration file for Cloudflare Wrangler, used to deploy and manage the worker. It includes settings like worker name, environment variables, and deployment targets. Update this file to configure deployment settings.

### `src/` Directory

The `src/` directory contains the main application logic, organized into subdirectories for modularity. Here's a breakdown:

- `src/configs/`\
  Contains configuration files for external services and resources, such as databases or third-party APIs. For example:

  - `redis.config.ts`: Initializes and manages a Redis client connection. It exports a function like `getRedisClient` to provide a singleton Redis client, connecting to a URL specified in environment variables.\
    Use this folder to centralize configurations for services like Redis, Firebase, or other external dependencies.

- `src/controllers/`\
  Contains controller files that orchestrate business logic for specific routes or endpoints. Controllers combine helpers, middlewares, and models to process incoming requests and return responses. For example, a controller might use a Firebase helper to fetch data, apply validation middleware, and use a model to structure and save data to a database.

- `src/helpers/`\
  Contains reusable helper functions that perform specific tasks, such as interacting with external services. For example:

  - A Firebase helper might fetch data from Firestore and format it for use in a controller.\
    Use this folder for service-specific logic that can be reused across controllers.

- `src/middlewares/`\
  Contains middleware functions for handling cross-cutting concerns, such as request validation, authentication, or logging. For example, a validation middleware might check the format of incoming request data before passing it to a controller. These are applied to routes to preprocess requests or responses.

- `src/models/`\
  Contains data models or schemas that define the structure of data used in the application. Models may include TypeScript interfaces or classes that shape data (e.g., for API responses or database entries) and logic to insert or update data in a database according to the defined structure.

- `src/routes/`\
  Contains route definitions that map HTTP endpoints to controller functions. Routes use controllers to handle requests, which in turn leverage helpers, middlewares, and models. Organize routes by feature or resource (e.g., `user.routes.ts`, `message.routes.ts`).

- `src/index.ts`\
  The entry point of the application. This file sets up the Cloudflare Worker, initializes routes, and applies global middleware or configuration setup (e.g., from `src/configs/`).

- `src/types/`\
  Contains custom TypeScript type definitions or interfaces specific to the application. Use this folder to define types for API payloads, database models, or configuration objects.

- `src/utils/`\
  Contains general-purpose utility functions, such as string manipulation, currency formatting, or date handling. These utilities are used across the application to perform common tasks not tied to specific services or business logic.

### `test/` Directory

The `test/` directory contains test files and configurations for testing the application using Vitest. Here's a breakdown:

- `test/env.d.ts`\
  A TypeScript declaration file for defining types related to the test environment, such as mocked APIs or environment variables used in tests.

- `test/index.spec.ts`\
  Contains test cases for the main application logic, typically testing the entry point (`index.ts`) or core functionality. Follow a naming convention like `*.spec.ts` or `*.test.ts` for test files.

- `test/tsconfig.json`\
  A TypeScript configuration file specific to the test environment. It may extend the root `tsconfig.json` and include test-specific settings, such as paths to test utilities or mocks.

## Application Flow

The application follows a modular flow where:

1. **Routes** (`src/routes/`) define endpoints and map them to **controllers** (`src/controllers/`).
2. **Controllers** orchestrate logic by:
   - Using **helpers** (`src/helpers/`) for tasks like fetching data from Firestore or other services.
   - Applying **middlewares** (`src/middlewares/`) for validation, authentication, or other preprocessing.
   - Using **models** (`src/models/`) to structure and persist data to a database according to defined interfaces or schemas.
   - Leveraging **utils** (`src/utils/`) for general-purpose tasks like string manipulation or currency formatting.
3. **Configurations** (`src/configs/`) provide initialized clients (e.g., Redis via `redis.config.ts`) or settings for external services, used by helpers or controllers.
4. The **entry point** (`src/index.ts`) ties everything together, setting up the worker and routing logic.

## Getting Started

1. **Install Dependencies**: Run `npm install` or `yarn install` to set up the project and generate the `node_modules/` folder.
2. **Development**:
   - Place application logic in the `src/` directory, organized into `configs/`, `controllers/`, `helpers/`, `middlewares/`, `models/`, `routes/`, `types/`, and `utils/`.
   - Use `index.ts` as the entry point for the worker.
   - Configure external services in `src/configs/` (e.g., `redis.config.ts` for Redis).
3. **Testing**:
   - Write tests in the `test/` directory, using `index.spec.ts` for core tests and adding feature-specific tests as needed.
   - Run tests with `npm test` or `yarn test`, configured via `vitest.config.mts`.
4. **Deployment**:
   - Configure `wrangler.jsonc` for Cloudflare Worker deployment.
   - Use `wrangler deploy` to deploy the worker.
5. **TypeScript**: Ensure TypeScript files adhere to the settings in `tsconfig.json` (root) and `test/tsconfig.json` (for tests). Use `worker-configuration.d.ts` and `src/types/` for type definitions.

## Best Practices

- Organize `src/` subdirectories by feature or responsibility for maintainability.
- Write unit and integration tests for controllers, helpers, and models in the `test/` directory.
- Keep configuration files in `src/configs/` to centralize environment-specific settings (e.g., Redis or Firebase connections).
- Use `src/middlewares/` for reusable request/response processing logic, such as validation or authentication.
- Define data models and schemas in `src/models/` to ensure consistent data handling.
- Place reusable, non-service-specific functions (e.g., string or currency utilities) in `src/utils/`.
- Define custom types in `src/types/` to ensure type safety across the application.
- Regularly update `package.json` and `package-lock.json` when adding or updating dependencies.
- Avoid committing the `node_modules/` folder to version control; ensure it's excluded via `.gitignore`.
READMEEOF

# Create .vscode/launch.json
echo -e "${WHITE}Creating .vscode/launch.json...${NC}"
mkdir -p .vscode
cat > .vscode/launch.json << 'LAUNCHEOF'
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Cloudflare Worker (dev)",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "wrangler",
      "runtimeArgs": ["dev", "--inspector-port=9229"],
      "cwd": "${workspaceFolder}",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "restart": true,
      "sourceMaps": true,
      "resolveSourceMapLocations": [
        "${workspaceFolder}/**",
        "!**/node_modules/**"
      ],
      "skipFiles": ["<node_internals>/**"],
      "env": {
        "NODE_OPTIONS": "--enable-source-maps"
      }
    },
    {
      "name": "Attach to Wrangler Inspector",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "restart": false,
      "sourceMaps": true,
      "resolveSourceMapLocations": [
        "${workspaceFolder}/**",
        "!**/node_modules/**"
      ],
      "skipFiles": ["<node_internals>/**"]
    }
  ]
}
LAUNCHEOF

# Create folder structure in src
echo -e "${WHITE}Creating folder structure...${NC}"
mkdir -p src/configs
mkdir -p src/controllers
mkdir -p src/helpers
mkdir -p src/middlewares
mkdir -p src/models
mkdir -p src/routes
mkdir -p src/types
mkdir -p src/utils

echo ""
echo -e "${WHITE}========================================${NC}"
echo -e "${WHITE}Setup Complete!${NC}"
echo -e "${WHITE}========================================${NC}"
echo ""
echo -e "${WHITE}Your project structure:${NC}"
echo "."
echo "├── .vscode"
echo "│   └── launch.json"
echo "├── configs"
echo "├── controllers"
echo "├── helpers"
echo "├── middlewares"
echo "├── models"
echo "├── routes"
echo "├── index.ts"
echo "├── types"
echo "└── utils"
echo ""
echo -e "${ORANGE}Next steps:${NC}"
echo "1. cd $PROJECT_NAME"
echo "2. npm run start    (to start development server)"
echo "3. npm run deploy   (to deploy to Cloudflare)"
echo "4. Open in VS Code and use the 'Debug Cloudflare Worker (dev)' configuration to debug"
echo ""